name: Scrambler
description: Word Typing Game!
version: 1.1
main: com.kong.Scrambler.Scrambler
authors: [Kong]
commands:
  scrambler:
    description:
    usage: /<command>
permissions:
  scrambler.*:
    description: Access all commands in Scrambler
    default: op
  scrambler.pause:
    description: Pause Scrambler timer
    default: op
  scrambler.start:
    description: Start Scrambler timer
    default: op
  scrambler.forcestop:
    description: Stop a running Scrambler game
    default: op
  scrambler.forcestart:
    description: Force start a Scrambler game
    default: op